//! Every keyword of the `lol!` macro, compiled through the macro
//!
//! Generated by `scripts/macro_kinds.py --write` from the keyword arms of
//! `alice-lol-macro/src/parser.rs` (do not edit) A node kind whose emitted
//! constructor does not match `alice-sdf` fails to compile here CI also compiles
//! this file against `alice-sdf` from crates.io (`scripts/registry_consumer.sh`)

use alice_lol::{lol, SdfNode};

/// the number of keywords in the macro's parser
const KEYWORDS: usize = 124;
const _: () = assert!(KEYWORDS > 0, "no keyword compiled");

#[rustfmt::skip]
#[allow(clippy::too_many_lines, reason = "one line per keyword of the macro's parser")]
fn every_kind() -> Vec<(&'static str, SdfNode)> {
    vec![
        ("sphere", lol! { sphere(3.0) }),
        ("box3d", lol! { box3d(3.0, 3.0, 3.0) }),
        ("rounded_box", lol! { rounded_box(3.0, 3.0, 3.0, 3.0) }),
        ("cylinder", lol! { cylinder(3.0, 3.0) }),
        ("torus", lol! { torus(3.0, 3.0) }),
        ("cone", lol! { cone(3.0, 3.0) }),
        ("capsule", lol! { capsule(3.0, 3.0) }),
        ("ellipsoid", lol! { ellipsoid(3.0, 3.0, 3.0) }),
        ("plane", lol! { plane(3.0, 3.0, 3.0, 3.0) }),
        ("octahedron", lol! { octahedron(3.0) }),
        ("rounded_cone", lol! { rounded_cone(3.0, 3.0, 3.0) }),
        ("pyramid", lol! { pyramid(3.0) }),
        ("hex_prism", lol! { hex_prism(3.0, 3.0) }),
        ("link", lol! { link(3.0, 3.0, 3.0) }),
        ("capped_cone", lol! { capped_cone(3.0, 3.0, 3.0) }),
        ("capped_torus", lol! { capped_torus(3.0, 3.0, 3.0) }),
        ("rounded_cylinder", lol! { rounded_cylinder(3.0, 3.0, 3.0) }),
        ("tube", lol! { tube(3.0, 3.0, 3.0) }),
        ("barrel", lol! { barrel(3.0, 3.0, 3.0) }),
        ("heart", lol! { heart(3.0) }),
        ("egg", lol! { egg(3.0, 3.0) }),
        ("helix", lol! { helix(3.0, 3.0, 3.0, 3.0) }),
        ("tetrahedron", lol! { tetrahedron(3.0) }),
        ("box_frame", lol! { box_frame(3.0, 3.0, 3.0, 3.0) }),
        ("diamond", lol! { diamond(3.0, 3.0) }),
        ("star_polygon", lol! { star_polygon(3.0, 3.0, 3.0, 3.0) }),
        ("cross_shape", lol! { cross_shape(3.0, 3.0, 3.0, 3.0) }),
        ("union", lol! { union(sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("smooth_union", lol! { smooth_union(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("intersection", lol! { intersection(sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("smooth_intersection", lol! { smooth_intersection(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("subtract", lol! { subtract(sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("smooth_subtract", lol! { smooth_subtract(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("chamfer_union", lol! { chamfer_union(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("chamfer_intersection", lol! { chamfer_intersection(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("chamfer_subtraction", lol! { chamfer_subtraction(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("stairs_union", lol! { stairs_union(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("stairs_intersection", lol! { stairs_intersection(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("stairs_subtraction", lol! { stairs_subtraction(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("xor", lol! { xor(sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("pipe", lol! { pipe(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("engrave", lol! { engrave(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("groove", lol! { groove(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("tongue", lol! { tongue(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("columns_union", lol! { columns_union(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("columns_intersection", lol! { columns_intersection(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("columns_subtraction", lol! { columns_subtraction(3.0, 3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("exp_smooth_union", lol! { exp_smooth_union(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("exp_smooth_intersection", lol! { exp_smooth_intersection(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("exp_smooth_subtraction", lol! { exp_smooth_subtraction(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("translate", lol! { translate(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("rotate", lol! { rotate(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("scale", lol! { scale(3.0, sphere(1.0)) }),
        ("scale_non_uniform", lol! { scale_non_uniform(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("round", lol! { round(3.0, sphere(1.0)) }),
        ("onion", lol! { onion(3.0, sphere(1.0)) }),
        ("twist", lol! { twist(3.0, sphere(1.0)) }),
        ("bend", lol! { bend(3.0, sphere(1.0)) }),
        ("mirror", lol! { mirror(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("repeat", lol! { repeat(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("elongate", lol! { elongate(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("revolution", lol! { revolution(3.0, sphere(1.0)) }),
        ("extrude", lol! { extrude(3.0, sphere(1.0)) }),
        ("taper", lol! { taper(3.0, sphere(1.0)) }),
        ("displacement", lol! { displacement(3.0, sphere(1.0)) }),
        ("polar_repeat", lol! { polar_repeat(3.0, sphere(1.0)) }),
        ("shear", lol! { shear(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("noise", lol! { noise(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("repeat_finite", lol! { repeat_finite(3.0, 3.0, 3.0, 3.0, 3.0, 3.0, sphere(1.0)) }),
        ("octant_mirror", lol! { octant_mirror(sphere(1.0)) }),
        ("icosahedral_symmetry", lol! { icosahedral_symmetry(sphere(1.0)) }),
        ("with_material", lol! { with_material(3.0, sphere(1.0)) }),
        ("surface_roughness", lol! { surface_roughness(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("animate", lol! { animate(3.0, 3.0, sphere(1.0)) }),
        ("morph", lol! { morph(3.0, sphere(1.0), box3d(1.0, 1.0, 1.0)) }),
        ("triangle", lol! { triangle(3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0) }),
        ("bezier", lol! { bezier(3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0) }),
        ("triangular_prism", lol! { triangular_prism(3.0, 3.0) }),
        ("cut_sphere", lol! { cut_sphere(3.0, 3.0) }),
        ("cut_hollow_sphere", lol! { cut_hollow_sphere(3.0, 3.0, 3.0) }),
        ("death_star", lol! { death_star(3.0, 3.0, 3.0) }),
        ("solid_angle", lol! { solid_angle(3.0, 3.0) }),
        ("rhombus", lol! { rhombus(3.0, 3.0, 3.0, 3.0) }),
        ("horseshoe", lol! { horseshoe(3.0, 3.0, 3.0, 3.0, 3.0) }),
        ("vesica", lol! { vesica(3.0, 3.0) }),
        ("infinite_cylinder", lol! { infinite_cylinder(3.0) }),
        ("infinite_cone", lol! { infinite_cone(3.0) }),
        ("gyroid", lol! { gyroid(3.0, 3.0) }),
        ("chamfered_cube", lol! { chamfered_cube(3.0, 3.0, 3.0, 3.0) }),
        ("schwarz_p", lol! { schwarz_p(3.0, 3.0) }),
        ("superellipsoid", lol! { superellipsoid(3.0, 3.0, 3.0, 3.0, 3.0) }),
        ("rounded_x", lol! { rounded_x(3.0, 3.0, 3.0) }),
        ("pie", lol! { pie(3.0, 3.0, 3.0) }),
        ("trapezoid", lol! { trapezoid(3.0, 3.0, 3.0, 3.0) }),
        ("parallelogram", lol! { parallelogram(3.0, 3.0, 3.0, 3.0) }),
        ("tunnel", lol! { tunnel(3.0, 3.0, 3.0) }),
        ("uneven_capsule", lol! { uneven_capsule(3.0, 3.0, 3.0, 3.0) }),
        ("arc_shape", lol! { arc_shape(3.0, 3.0, 3.0, 3.0) }),
        ("moon", lol! { moon(3.0, 3.0, 3.0, 3.0) }),
        ("blobby_cross", lol! { blobby_cross(3.0, 3.0) }),
        ("parabola_segment", lol! { parabola_segment(3.0, 3.0, 3.0) }),
        ("regular_polygon", lol! { regular_polygon(3.0, 3.0, 3.0) }),
        ("stairs_prim", lol! { stairs_prim(3.0, 3.0, 3.0, 3.0) }),
        ("dodecahedron", lol! { dodecahedron(3.0) }),
        ("icosahedron", lol! { icosahedron(3.0) }),
        ("truncated_octahedron", lol! { truncated_octahedron(3.0) }),
        ("truncated_icosahedron", lol! { truncated_icosahedron(3.0) }),
        ("diamond_surface", lol! { diamond_surface(3.0, 3.0) }),
        ("neovius", lol! { neovius(3.0, 3.0) }),
        ("lidinoid", lol! { lidinoid(3.0, 3.0) }),
        ("iwp", lol! { iwp(3.0, 3.0) }),
        ("frd", lol! { frd(3.0, 3.0) }),
        ("fischer_koch_s", lol! { fischer_koch_s(3.0, 3.0) }),
        ("pmy", lol! { pmy(3.0, 3.0) }),
        ("circle_2d", lol! { circle_2d(3.0, 3.0) }),
        ("rect_2d", lol! { rect_2d(3.0, 3.0, 3.0) }),
        ("segment_2d", lol! { segment_2d(3.0, 3.0, 3.0, 3.0, 3.0, 3.0) }),
        ("rounded_rect_2d", lol! { rounded_rect_2d(3.0, 3.0, 3.0, 3.0) }),
        ("annular_2d", lol! { annular_2d(3.0, 3.0, 3.0) }),
        ("terrain", lol! { terrain(3.0, 3.0) }),
        ("sweep_bezier", lol! { sweep_bezier(3.0, 3.0, 3.0, 3.0, 3.0, 3.0, sphere(1.0)) }),
        ("lattice_infill", lol! { lattice_infill(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("diamond_infill", lol! { diamond_infill(3.0, 3.0, 3.0, sphere(1.0)) }),
        ("schwarz_infill", lol! { schwarz_infill(3.0, 3.0, 3.0, sphere(1.0)) }),
    ]
}

#[test]
fn every_keyword_of_the_macro_builds_a_node() {
    let kinds = every_kind();
    assert_eq!(kinds.len(), KEYWORDS);
    let mut names: Vec<&str> = kinds.iter().map(|(k, _)| *k).collect();
    names.sort_unstable();
    names.dedup();
    assert_eq!(names.len(), KEYWORDS, "a keyword is listed twice");
    for (kw, node) in &kinds {
        assert!(node.node_count() > 0, "{kw}: empty node");
    }
}
