#!/usr/bin/env python3
"""Every keyword of the `lol!` macro, compiled through the macro.

The keyword list is read from `alice-lol-macro/src/parser.rs` (the arms of `parse_expr`),
and the arguments of each keyword from the argument readers its arm calls in order
(`parse_2f` = two numbers, `parse_1f_child` = a number and a child, ...). The test file
`alice-lol/tests/macro_every_kind.rs` is generated from that list: one `lol!` call per
keyword, so a node kind whose emitted constructor no longer matches `alice-sdf` fails to
compile. CI compiles the same file against `alice-sdf` from crates.io
(`scripts/registry_consumer.sh`), where the published versions are what a user gets.

usage: macro_kinds.py --write | --check
Exit 1 when the test file is not the generated one, 2 when no keyword was read.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PARSER = ROOT / "alice-lol-macro" / "src" / "parser.rs"
TEST = ROOT / "alice-lol" / "tests" / "macro_every_kind.rs"

NUM = "3.0"  # one value for every number: a size, a count of 3, an angle, a smoothing width
CHILD = "sphere(1.0)"
CHILD2 = "box3d(1.0, 1.0, 1.0)"

# argument reader -> what it reads, in order ("n" = a number, "c" = a child expression)
SHAPES = {
    "parse_val": "n",
    "parse_expr": "c",
    "parse_child_only": "c",
    "parse_children": "cc",
    "parse_k_children": "ncc",
    "parse_2f_children": "nncc",
    "parse_1f_ab": "ncc",
    "parse_2f_ab": "nncc",
}


def shape_of(reader: str) -> str:
    if reader in SHAPES:
        return SHAPES[reader]
    m = re.fullmatch(r"parse_(\d+)f(_child)?", reader)
    if not m:
        raise SystemExit(f"error: unknown argument reader {reader}")
    return "n" * int(m.group(1)) + ("c" if m.group(2) else "")


def keywords() -> list[tuple[str, str]]:
    src = PARSER.read_text(encoding="utf-8")
    body = src[src.index("fn parse_expr(") :]
    body = body[: body.index("\n        other =>")] if "\n        other =>" in body else body
    parts = re.split(r'\n        "([a-z_0-9]+)" => \{', body)
    out = []
    for k in range(1, len(parts), 2):
        readers = re.findall(r"\b(parse_[a-z0-9_]+)\(&content\)", parts[k + 1])
        if not readers:
            raise SystemExit(f"error: keyword {parts[k]} calls no argument reader")
        out.append((parts[k], "".join(shape_of(r) for r in readers)))
    return out


def call(kw: str, shape: str) -> str:
    children = iter([CHILD, CHILD2, CHILD, CHILD2])
    return f"{kw}({', '.join(NUM if a == 'n' else next(children) for a in shape)})"


def render(kws: list[tuple[str, str]]) -> str:
    lines = [
        "//! Every keyword of the `lol!` macro, compiled through the macro",
        "//!",
        "//! Generated by `scripts/macro_kinds.py --write` from the keyword arms of",
        "//! `alice-lol-macro/src/parser.rs` (do not edit) A node kind whose emitted",
        "//! constructor does not match `alice-sdf` fails to compile here CI also compiles",
        "//! this file against `alice-sdf` from crates.io (`scripts/registry_consumer.sh`)",
        "",
        "use alice_lol::{lol, SdfNode};",
        "",
        "/// the number of keywords in the macro's parser",
        f"const KEYWORDS: usize = {len(kws)};",
        "const _: () = assert!(KEYWORDS > 0, \"no keyword compiled\");",
        "",
        "#[rustfmt::skip]",
        "#[allow(clippy::too_many_lines, reason = \"one line per keyword of the macro's parser\")]",
        "fn every_kind() -> Vec<(&'static str, SdfNode)> {",
        "    vec![",
    ]
    lines += [f'        ("{kw}", lol! {{ {call(kw, shape)} }}),' for kw, shape in kws]
    lines += [
        "    ]",
        "}",
        "",
        "#[test]",
        "fn every_keyword_of_the_macro_builds_a_node() {",
        "    let kinds = every_kind();",
        "    assert_eq!(kinds.len(), KEYWORDS);",
        "    let mut names: Vec<&str> = kinds.iter().map(|(k, _)| *k).collect();",
        "    names.sort_unstable();",
        "    names.dedup();",
        "    assert_eq!(names.len(), KEYWORDS, \"a keyword is listed twice\");",
        "    for (kw, node) in &kinds {",
        "        assert!(node.node_count() > 0, \"{kw}: empty node\");",
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if argv not in (["--write"], ["--check"]):
        print(__doc__.strip().splitlines()[-2], file=sys.stderr)
        return 2
    kws = keywords()
    if not kws:
        print("error: read 0 keywords from the macro's parser", file=sys.stderr)
        return 2
    text = render(kws)
    if argv == ["--write"]:
        TEST.write_text(text, encoding="utf-8", newline="\n")
        print(f"macro kinds: wrote {len(kws)} keywords")
        return 0
    have = TEST.read_text(encoding="utf-8") if TEST.exists() else ""
    if have != text:
        print(f"error: {TEST.relative_to(ROOT)} is not the generated file for the {len(kws)} keywords "
              "of the macro's parser; run scripts/macro_kinds.py --write", file=sys.stderr)
        return 1
    print(f"macro kinds: compared {len(kws)} keywords, test file is current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
