#!/usr/bin/env bash
# The packaged `alice-lol`, built the way a user gets it: its dependencies from crates.io.
#
# Inside this workspace every sibling crate (`alice-sdf`, `alice-zip`, ...) is a path to a
# checkout of its main branch, so the build never sees the versions a published
# `alice-lol` resolves to. This script packages `alice-lol-macro` and `alice-lol`, puts the
# packaged `alice-lol` into a throwaway crate (the packaged manifest has no paths: every
# dependency is its version requirement on crates.io), and compiles there:
#   - `alice-lol/tests/macro_every_kind.rs` (every keyword of the macro, generated by
#     `scripts/macro_kinds.py`), so an emitted constructor that does not match the published
#     `alice-sdf` fails to compile;
#   - the lock of that build has one version of each `alice-*` crate.
# The macro is taken from its package (a `[patch]`), because `alice-lol` requires the
# version this workspace is about to publish; that the published macro is the same source
# as the local one is `scripts/published_source_check.py`.
#
# usage: scripts/registry_consumer.sh
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
OUT=${REGISTRY_CONSUMER_DIR:-$ROOT/target/registry-consumer}
rm -rf "$OUT"
mkdir -p "$OUT/pkg" "$OUT/tests"

cd "$ROOT"
python3 scripts/macro_kinds.py --check
cargo package -q -p alice-lol-macro -p alice-lol --no-verify ${REGISTRY_CONSUMER_ALLOW_DIRTY:+--allow-dirty}
version() { sed -n 's/^version = "\(.*\)"/\1/p' "$1" | head -1; }
LOL=$(version alice-lol/Cargo.toml)
MACRO=$(version alice-lol-macro/Cargo.toml)
for c in "alice-lol-$LOL" "alice-lol-macro-$MACRO"; do
  # -m: the package stores one fixed mtime for every file, so a reused build directory
  # would not see a changed source; extract with the current time instead
  tar -xmzf "target/package/$c.crate" -C "$OUT/pkg"
done
if awk '/^\[/{dep=($0 ~ /dependencies/)} dep && /^path *=/' "$OUT/pkg/alice-lol-$LOL/Cargo.toml" | grep .; then
  echo "error: the packaged alice-lol manifest still has a path dependency" >&2
  exit 1
fi

cat > "$OUT/Cargo.toml" <<EOF
[package]
name = "lol-registry-consumer"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
alice-lol = { path = "pkg/alice-lol-$LOL" }

[patch.crates-io]
alice-lol-macro = { path = "pkg/alice-lol-macro-$MACRO" }

[workspace]
EOF
mkdir -p "$OUT/src"
echo "" > "$OUT/src/lib.rs"
cp alice-lol/tests/macro_every_kind.rs "$OUT/tests/"

LOG="$OUT/test.log"
CARGO_TARGET_DIR="${REGISTRY_CONSUMER_TARGET:-$ROOT/target/registry-consumer-target}" cargo test --manifest-path "$OUT/Cargo.toml" --test macro_every_kind 2>&1 | tee "$LOG"

# the build used the packaged macro and crates.io for the siblings
lock="$OUT/Cargo.lock"
block() { awk -v n="$1" '/^\[\[package\]\]/{p=0} $0=="name = \""n"\""{p=1} p' "$lock"; }
if block alice-lol-macro | grep -q '^source'; then
  echo "error: the [patch] for alice-lol-macro was not used (alice-lol requires another version)" >&2
  exit 1
fi
for c in alice-sdf alice-det-math; do
  if ! block "$c" | grep -q '^source = "registry+'; then
    echo "error: $c is not from crates.io in the consumer's lock" >&2
    exit 1
  fi
done
grep -q '^test every_keyword_of_the_macro_builds_a_node \.\.\. ok' "$LOG" || {
  echo "error: the every-keyword test did not run" >&2
  exit 1
}
EMPTY=$(mktemp)
python3 scripts/lock_single_version.py --lock "$lock" --baseline "$EMPTY"
rm -f "$EMPTY"
echo "registry consumer: alice-lol $LOL + alice-lol-macro $MACRO built against crates.io ($(block alice-sdf | sed -n 's/^version = //p' | tr -d '"') alice-sdf)"
