#!/usr/bin/env python3
"""scripts/lock_single_version.py の試験.

各 case は小さな lock と baseline を一時 directory に作り、1 箇所だけ崩して
検査器がそれを報告することを確かめる 最初の case はこの repo 自身に掛ける
crate 名は架空のもの (`alice-sample-*`) を使う
"""

from __future__ import annotations

import os
import sys
import tempfile
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import lock_single_version as lsv  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def pkg(name: str, version: str, source: bool = True) -> str:
    src = '\nsource = "registry+https://github.com/rust-lang/crates.io-index"' if source else ""
    return f'[[package]]\nname = "{name}"\nversion = "{version}"{src}\n'


CLEAN = (
    "# This file is automatically @generated by Cargo.\n"
    "version = 4\n\n"
    + pkg("alice-sample-law", "1.2.0")
    + "\n"
    + pkg("alice-sample-math", "0.4.0")
    + "\n"
    # third-party の重複は対象外
    + pkg("thiserror", "1.0.69")
    + "\n"
    + pkg("thiserror", "2.0.20")
    + "\n"
    + pkg("syn", "2.0.119")
    + "\n"
    + pkg("syn", "3.0.4")
    + "\n"
)


def run(lock: str, baseline: str | None = None) -> tuple[list[str], dict[str, int]]:
    d = tempfile.mkdtemp()
    lock_path = os.path.join(d, "Cargo.lock")
    with open(lock_path, "w", encoding="utf-8") as f:
        f.write(lock)
    base_path = os.path.join(d, "baseline.txt")
    if baseline is not None:
        with open(base_path, "w", encoding="utf-8") as f:
            f.write(baseline)
    return lsv.check(lock_path, base_path)


class RealRepo(unittest.TestCase):
    def test_this_repository_passes(self):
        errs, counts = lsv.check(
            os.path.join(ROOT, "Cargo.lock"),
            os.path.join(ROOT, "scripts", "lock-duplicates-baseline.txt"),
        )
        self.assertEqual(errs, [])
        self.assertGreater(counts["packages"], 50)
        self.assertGreater(counts["alice packages"], 0)


class Duplicates(unittest.TestCase):
    def test_a_clean_lock_passes(self):
        errs, counts = run(CLEAN, "")
        self.assertEqual(errs, [])
        self.assertEqual(counts["duplicates"], 0)
        self.assertEqual(counts["alice packages"], 2)

    def test_third_party_duplicates_are_not_reported(self):
        _, counts = run(CLEAN, "")
        self.assertEqual(counts["packages"], 4)  # 2 alice + thiserror + syn

    def test_a_new_alice_duplicate_fails(self):
        errs, counts = run(CLEAN + "\n" + pkg("alice-sample-math", "0.3.2"), "")
        self.assertEqual(counts["duplicates"], 1)
        self.assertTrue(any("alice-sample-math" in e and "0.3.2 0.4.0" in e for e in errs), errs)

    def test_a_duplicate_listed_in_the_baseline_passes(self):
        errs, _ = run(
            CLEAN + "\n" + pkg("alice-sample-math", "0.3.2"),
            "# 既知\nalice-sample-math 0.3.2 0.4.0\n",
        )
        self.assertEqual(errs, [])

    def test_a_baseline_row_with_other_versions_fails(self):
        errs, _ = run(
            CLEAN + "\n" + pkg("alice-sample-math", "0.3.2"),
            "alice-sample-math 0.3.1 0.4.0\n",
        )
        self.assertTrue(any("版の組が baseline と違う" in e for e in errs), errs)

    def test_a_resolved_baseline_row_fails(self):
        errs, _ = run(CLEAN, "alice-sample-math 0.3.2 0.4.0\n")
        self.assertTrue(any("解消済" in e for e in errs), errs)

    def test_a_baseline_row_for_a_crate_that_left_the_lock_fails(self):
        errs, _ = run(CLEAN, "alice-sample-gone 0.1.0 0.2.0\n")
        self.assertTrue(any("lock に無い" in e for e in errs), errs)

    def test_three_versions_are_reported_in_order(self):
        lock = CLEAN + "\n" + pkg("alice-sample-math", "0.3.2") + "\n" + pkg("alice-sample-math", "0.10.0")
        errs, _ = run(lock, "")
        self.assertTrue(any("0.3.2 0.4.0 0.10.0" in e for e in errs), errs)


class NothingCompared(unittest.TestCase):
    def test_an_empty_lock_fails(self):
        errs, counts = run("version = 4\n", "")
        self.assertEqual(counts["packages"], 0)
        self.assertTrue(any("`packages` が 1 件も比べていない" in e for e in errs), errs)

    def test_a_lock_without_alice_packages_fails(self):
        errs, _ = run(pkg("serde", "1.0.0"), "")
        self.assertTrue(any("`alice packages` が 1 件も比べていない" in e for e in errs), errs)

    def test_a_missing_lock_fails(self):
        d = tempfile.mkdtemp()
        errs, counts = lsv.check(os.path.join(d, "Cargo.lock"), os.path.join(d, "baseline.txt"))
        self.assertEqual(counts["packages"], 0)
        self.assertTrue(any("text として読めない" in e for e in errs), errs)

    def test_a_binary_lock_fails(self):
        d = tempfile.mkdtemp()
        p = os.path.join(d, "Cargo.lock")
        with open(p, "wb") as f:
            f.write(b"\xff\xfe\x00binary")
        errs, _ = lsv.check(p, os.path.join(d, "baseline.txt"))
        self.assertTrue(any("text として読めない" in e for e in errs), errs)


class Parsing(unittest.TestCase):
    def test_a_name_without_a_version_line_is_not_a_package(self):
        # `[[patch.unused]]` 等の name だけの節を package と数えない
        errs, counts = run(CLEAN + '\n[[patch.unused]]\nname = "alice-sample-law"\n', "")
        self.assertEqual(counts["alice packages"], 2)
        self.assertEqual(errs, [])

    def test_the_versions_of_a_baseline_row_may_be_written_in_any_order(self):
        errs, _ = run(
            CLEAN + "\n" + pkg("alice-sample-math", "0.3.2"),
            "alice-sample-math 0.4.0 0.3.2\n",
        )
        self.assertEqual(errs, [])

    def test_a_comment_only_baseline_is_empty(self):
        errs, counts = run(CLEAN, "# 何も無い\n\n")
        self.assertEqual(counts["baseline rows"], 0)
        self.assertEqual(errs, [])


if __name__ == "__main__":
    unittest.main(verbosity=2)
